Parameters:
  DBName:
    Type: String
  User:
    Type: String
  Pass:
    Type: String
    Description: "Minimo 8 caracters"
Resources:
  MyDBvideoInstance:
    Type: AWS::RDS::DBInstance
    Properties: 
      DBName: !Ref DBName
      MasterUsername: !Ref User
      MasterUserPassword: !Ref Pass
      Engine: MySQL
      DBInstanceClass: db.t2.micro
      StorageType: gp2
      PubliclyAccessible: True
      AllocatedStorage: "20"
      DBInstanceIdentifier: !Join ["-", ["MyDbInstance", !Ref "AWS::Region"]]
      AvailabilityZone: !Select [1, !GetAZs ""]